[package]
name = "builtins"
version = "0.1.0"
edition = "2024"

[dependencies]
sys = { path = "../../unsafe/sys" }
error-stack = { version = "0.7", default-features = false }
displaydoc = "0.2"

[[bin]]
name = "builtin_exec_ok"
path = "tests/bins/builtin_exec_ok.rs"
test = false
doctest = false

[lints]
workspace = true
