//! The fdshell builtins (the `DISPATCH` table in `child/dispatch.rs` plus the
//! `import_fd`/`export_fd` fd-pass builtins in `child/fdpass.rs`).

pub(crate) const BUILTINS: &[(&[u8], &[u8])] = &[
    (b"[", b"Test expression (alias for test)"),
    (b"accept", b"Accept a connection on a listening fd var"),
    (b"bind", b"Create a socket and bind it to an address"),
    (b"connect", b"Create a socket and connect it to a peer"),
    (b"copy_file_range", b"Zero-copy copy between two fd vars"),
    (b"echo", b"Print arguments"),
    (b"eventfd", b"Counter fd that arms on non-zero"),
    (b"exec_at", b"Execute with path lookup"),
    (b"exec_fd", b"Execute with fd lookup"),
    (b"explain", b"Show provenance of a variable"),
    (b"fallocate", b"Reserve disk space for a file"),
    (b"false", b"Exit with failure status"),
    (b"fchmod", b"Change file mode"),
    (b"fdexplain", b"Show provenance of an fd variable"),
    (b"flock", b"Advisory lock on an fd var"),
    (b"fsync", b"Flush an fd to storage"),
    (b"ftruncate", b"Truncate a file to a length"),
    (b"help", b"List available commands"),
    (b"import_fd", b"Import an fd from the parent"),
    (b"listen", b"Create, bind, and listen on a socket"),
    (b"ls", b"List a directory's entry names"),
    (b"lseek", b"Move the offset of an fd"),
    (b"memfd", b"Create an in-memory file by fd"),
    (b"mkdirat", b"Create directory"),
    (b"mkfifoat", b"Create fifo and open it read-write"),
    (b"openat2", b"Open file"),
    (b"pipe", b"Create pipe"),
    (b"printf", b"Format and print arguments"),
    (b"pwd", b"Print working directory"),
    (b"readlink", b"Symlink target by path or fd"),
    (b"renameat2", b"Rename/move file"),
    (b"resolve", b"Resolve fd variables"),
    (b"statx", b"File metadata by path or fd"),
    (b"symlinkat", b"Create a symbolic link"),
    (b"test", b"Test expression (also '[')"),
    (b"timerfd", b"Timer as an fd source"),
    (b"true", b"Exit with success status"),
    (b"type", b"Show how a command name resolves"),
    (b"unlinkat", b"Remove a file or directory entry"),
    (b"utimensat", b"Set file atime/mtime"),
    (
        b"verity",
        b"fs-verity: query/check/enable a file digest, or dump its metadata",
    ),
];
